SyntaxError: The given name 'foo' is already used in another export [type_3.sts:20:27]
